/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tiles/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vector tile for a coord/zoom. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    z: number;
                    x: number;
                    y: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mapbox Vector Tile (protobuf) bytes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-protobuf": unknown;
                    };
                };
                /** @description Tile has no features at this z/x/y. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No installed region covers this tile. */
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated pmtiles metadata for all installed regions. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metadata blob. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            minZoom?: number;
                            maxZoom?: number;
                            bounds?: components["schemas"]["BBox"];
                            regions?: {
                                name?: string;
                                bounds?: components["schemas"]["BBox"];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/styles/{name}.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** MapLibre style JSON. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: "light" | "dark" | "print";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description MapLibre style JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sprites/{name}@{density}.{ext}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sprite sheet. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                    density: "1x" | "2x";
                    ext: "png" | "json";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sprite asset bytes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glyphs/{fontstack}/{range}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glyph ranges for text rendering. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fontstack: string;
                    range: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Glyph range protobuf. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/x-protobuf": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autocomplete search-as-you-type. */
        get: {
            parameters: {
                query: {
                    q: string;
                    "focus.lat"?: number;
                    "focus.lon"?: number;
                    limit?: number;
                    lang?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranked results. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results?: components["schemas"]["GeocodeResult"][];
                            traceId?: components["schemas"]["TraceID"];
                        };
                    };
                };
                400: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full-text search (for sentence-level queries). */
        get: {
            parameters: {
                query: {
                    q: string;
                    "focus.lat"?: number;
                    "focus.lon"?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranked results. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results?: components["schemas"]["GeocodeResult"][];
                            traceId?: components["schemas"]["TraceID"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reverse geocode a coordinate. */
        get: {
            parameters: {
                query: {
                    lat: number;
                    lon: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nearest address. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            result?: components["schemas"]["GeocodeResult"];
                            traceId?: components["schemas"]["TraceID"];
                        };
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute a route. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RouteRequest"];
                };
            };
            responses: {
                /** @description Routes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteResponse"];
                    };
                };
                400: components["responses"]["Error"];
                /** @description No region covers the request. */
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route/{id}/gpx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export a previously-computed route as GPX. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description GPX XML. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/gpx+xml": unknown;
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route/{id}/kml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export as KML. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description KML XML. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.google-earth.kml+xml": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Distance/time matrix. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MatrixRequest"];
                };
            };
            responses: {
                /** @description Matrix. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatrixResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/isochrone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reachable-in-time polygons. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IsochroneRequest"];
                };
            };
            responses: {
                /** @description GeoJSON FeatureCollection. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pois": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query POIs by bbox / text / category. */
        get: {
            parameters: {
                query?: {
                    /** @description minLon,minLat,maxLon,maxLat */
                    bbox?: string;
                    q?: string;
                    category?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description POI list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pois?: components["schemas"]["Poi"][];
                            traceId?: components["schemas"]["TraceID"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pois/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single POI. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description POI. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Poi"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pois/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Category taxonomy. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tree. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            categories?: components["schemas"]["PoiCategory"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List installed / in-progress regions. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            regions?: components["schemas"]["Region"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Install a region. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        schedule?: components["schemas"]["RegionSchedule"];
                    };
                };
            };
            responses: {
                /** @description Install job queued. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            region?: components["schemas"]["Region"];
                            jobId?: string;
                        };
                    };
                };
                /** @description Already installed or an active install exists. */
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available-to-install tree from Geofabrik. */
        get: {
            parameters: {
                query?: {
                    /** @description Bypass cache. */
                    force?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Catalogue tree. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            catalog?: components["schemas"]["RegionCatalogEntry"][];
                            /** Format: date-time */
                            fetchedAt?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Region state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Region"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        /** Uninstall (archive) a region. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted / archived. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            region?: components["schemas"]["Region"];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/{name}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Update job queued. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            jobId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/{name}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        schedule: components["schemas"]["RegionSchedule"];
                    };
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Region"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket for region + job events.
         * @description Client → server:
         *       { "type": "subscribe", "channel": "region.europe-romania" }
         *       { "type": "subscribe", "channel": "job.<id>" }
         *       { "type": "unsubscribe", "channel": "..." }
         *
         *     Server → client:
         *       { "type": "region.progress", "data": Region }
         *       { "type": "region.ready",    "data": Region }
         *       { "type": "region.failed",   "data": Region }
         *       { "type": "job.started",     "data": Job }
         *       { "type": "job.progress",    "data": Job }
         *       { "type": "job.complete",    "data": Job }
         *       { "type": "job.failed",      "data": Job }
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching Protocols. */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full settings tree. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsTree"];
                    };
                };
            };
        };
        /** Replace entire settings tree (validated against schema). */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsTree"];
                };
            };
            responses: {
                /** @description Replaced. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsTree"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Deep-merge partial settings. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsTree"];
                };
            };
            responses: {
                /** @description Merged. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsTree"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/settings/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** JSON schema for UI form generation (anonymous). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Schema + version wrapper. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsSchemaResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a short link. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uri */
                        url: string;
                    };
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShortLink"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to target URL. */
                301: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/og/preview.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-rendered OpenGraph PNG of a map state. */
        get: {
            parameters: {
                query: {
                    lat: number;
                    lon: number;
                    zoom?: number;
                    pin?: boolean;
                    width?: number;
                    height?: number;
                    style?: "light" | "dark" | "auto" | "print";
                    /** @description Canonical hyphenated region key (e.g. `europe-romania`). */
                    region?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PNG bytes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Minimal HTML viewer for iframe embedding. */
        get: {
            parameters: {
                query?: {
                    lat?: number;
                    lon?: number;
                    zoom?: number;
                    /** @description Drop a pin at `lat,lon` with an optional label, e.g. `44.42,26.10:Bucharest`. */
                    pin?: string;
                    style?: "light" | "dark" | "print";
                    /** @description Canonical hyphenated region key (e.g. `europe-romania`). */
                    region?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description HTML embed viewer. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": unknown;
                    };
                };
                /** @description Redirect to the UI origin when `LOCALMAPS_UI_ORIGIN` is set. */
                307: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Malformed query parameter. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Readiness. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            services?: {
                                redis?: boolean;
                                pmtiles?: boolean;
                                valhalla?: boolean;
                                pelias?: boolean;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Build info. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version?: string;
                            commit?: string;
                            builtAt?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/plain metrics. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a session via username + password. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Session cookie set; returns the authenticated user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                401: components["responses"]["Error"];
                429: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session cookie. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the current user's password. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        oldPassword: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users (admin-only). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users?: components["schemas"]["AuthUser"][];
                        };
                    };
                };
                403: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Create a user (admin-only). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                        /**
                         * @default admin
                         * @enum {string}
                         */
                        role?: "admin" | "viewer";
                    };
                };
            };
            responses: {
                /** @description User created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                400: components["responses"]["Error"];
                403: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user (admin-only). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                403: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Correlates a request across services. Every response includes one.
         * @example a7f3e9d1b2c4
         */
        TraceID: string;
        /** @enum {string} */
        ErrorCode: "BAD_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "INTERNAL" | "UPSTREAM_UNAVAILABLE" | "REGION_NOT_READY" | "REGION_NOT_INSTALLED" | "REGION_OUT_OF_COVERAGE" | "INVALID_REGION_NAME" | "JOB_NOT_FOUND" | "SCHEMA_MISMATCH" | "EGRESS_DENIED";
        ErrorResponse: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Human-safe message. Never includes stack traces or internal paths. */
                message: string;
                retryable: boolean;
                details?: {
                    [key: string]: unknown;
                };
            };
            traceId: components["schemas"]["TraceID"];
        };
        LatLon: {
            lat: number;
            lon: number;
        };
        /** @description [minLon, minLat, maxLon, maxLat] */
        BBox: number[];
        /** @enum {string} */
        RegionState: "not_installed" | "downloading" | "processing_tiles" | "processing_routing" | "processing_geocoding" | "processing_poi" | "ready" | "updating" | "failed" | "archived";
        /**
         * @description 'never' | 'daily' | 'weekly' | 'monthly' | cron string
         * @example monthly
         */
        RegionSchedule: string;
        Region: {
            /** @example europe/romania */
            name: string;
            /** @example Romania */
            displayName: string;
            /** @example europe */
            parent?: string | null;
            /** Format: uri */
            sourceUrl: string;
            sourcePbfBytes?: number | null;
            sourcePbfSha256?: string | null;
            bbox?: components["schemas"]["BBox"];
            state: components["schemas"]["RegionState"];
            stateDetail?: string | null;
            lastError?: string | null;
            /** Format: date-time */
            installedAt?: string | null;
            /** Format: date-time */
            lastUpdatedAt?: string | null;
            /** Format: date-time */
            nextUpdateAt?: string | null;
            schedule?: components["schemas"]["RegionSchedule"];
            diskBytes?: number | null;
            activeJobId?: string | null;
        };
        RegionCatalogEntry: {
            /** @example europe/romania */
            name: string;
            displayName: string;
            /** @enum {string} */
            kind: "continent" | "country" | "subregion";
            parent?: string | null;
            /** Format: uri */
            sourceUrl: string;
            sourcePbfBytes?: number | null;
            /** @example RO */
            iso3166_1?: string | null;
            estimatedBuildBytes?: number | null;
            children?: components["schemas"]["RegionCatalogEntry"][];
        };
        /** @enum {string} */
        JobState: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** @enum {string} */
        JobKind: "download_pbf" | "build_pmtiles" | "build_valhalla" | "build_pelias" | "build_overture" | "swap_region" | "update_region" | "archive_region";
        Job: {
            id: string;
            kind: components["schemas"]["JobKind"];
            region?: string | null;
            state: components["schemas"]["JobState"];
            /** Format: float */
            progress?: number | null;
            message?: string | null;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            error?: string | null;
            parentJobId?: string | null;
        };
        GeocodeResult: {
            id: string;
            label: string;
            category?: string | null;
            address?: {
                [key: string]: string;
            };
            center: components["schemas"]["LatLon"];
            bbox?: components["schemas"]["BBox"];
            confidence: number;
            /** @description Installed region that provided the result */
            region?: string | null;
        };
        /** @enum {string} */
        RouteMode: "auto" | "bicycle" | "pedestrian" | "truck";
        RouteRequest: {
            locations: components["schemas"]["LatLon"][];
            mode: components["schemas"]["RouteMode"];
            /** @default false */
            avoidHighways: boolean;
            /** @default false */
            avoidTolls: boolean;
            /** @default false */
            avoidFerries: boolean;
            /** @default 0 */
            alternatives: number;
            /**
             * @default metric
             * @enum {string}
             */
            units: "metric" | "imperial";
            language?: string | null;
            truck?: {
                heightMeters?: number;
                widthMeters?: number;
                weightTons?: number;
                lengthMeters?: number;
            } | null;
        };
        RouteLeg: {
            summary: {
                timeSeconds?: number;
                distanceMeters?: number;
            };
            maneuvers: {
                instruction: string;
                beginShapeIndex: number;
                endShapeIndex?: number;
                distanceMeters?: number;
                timeSeconds?: number;
                type?: string;
                streetName?: string | null;
            }[];
            geometry: {
                /** @description Google-style encoded polyline (precision 6). */
                polyline: string;
            };
        };
        Route: {
            /** @description Opaque id; use for GPX/KML export. */
            id: string;
            summary: {
                timeSeconds?: number;
                distanceMeters?: number;
            };
            legs: components["schemas"]["RouteLeg"][];
            waypoints?: components["schemas"]["LatLon"][];
            mode?: components["schemas"]["RouteMode"];
        };
        RouteResponse: {
            routes: components["schemas"]["Route"][];
            traceId: components["schemas"]["TraceID"];
        };
        IsochroneRequest: {
            origin: components["schemas"]["LatLon"];
            mode?: components["schemas"]["RouteMode"];
            /** @description Seconds of travel for each isochrone polygon (e.g. [600, 1800, 3600]) */
            contoursSeconds: number[];
        };
        MatrixRequest: {
            sources: components["schemas"]["LatLon"][];
            targets: components["schemas"]["LatLon"][];
            mode: components["schemas"]["RouteMode"];
        };
        MatrixResponse: {
            /** @description sources x targets; each cell {timeSeconds, distanceMeters} */
            matrix: {
                timeSeconds?: number;
                distanceMeters?: number;
            }[][];
            traceId: components["schemas"]["TraceID"];
        };
        Poi: {
            id: string;
            label: string;
            category?: string | null;
            center: components["schemas"]["LatLon"];
            tags?: {
                [key: string]: string;
            };
            /** @enum {string} */
            source?: "overture" | "osm";
            region?: string | null;
        };
        PoiCategory: {
            id: string;
            label: string;
            icon?: string | null;
            children?: components["schemas"]["PoiCategory"][];
        };
        /** @description Full settings tree. See docs/07-config-schema.md. */
        SettingsTree: {
            [key: string]: unknown;
        };
        /** @description One node in the settings schema (primitive, enum, object, or array). */
        SettingsSchemaNode: {
            /** @description Dot-path of this node in the settings tree (e.g. `map.style`). */
            key?: string;
            /** @enum {string} */
            type: "object" | "string" | "integer" | "number" | "boolean" | "enum" | "array";
            description?: string;
            default?: unknown;
            enumValues?: string[];
            minimum?: number;
            maximum?: number;
            items?: components["schemas"]["SettingsSchemaNode"];
            properties?: {
                [key: string]: components["schemas"]["SettingsSchemaNode"];
            };
            /** @description UI grouping hint (e.g. `map`, `routing`). Defaults to first segment of `key`. */
            uiGroup?: string;
            /** @description Optional unit for display (e.g. `seconds`, `px`, `GB`). */
            unit?: string;
            /** @description Suggested step for numeric inputs. */
            step?: number;
            /**
             * @description For arrays: element type.
             * @enum {string}
             */
            itemType?: "string" | "integer" | "number" | "boolean" | "object";
            /** @default false */
            readOnly: boolean;
            /** @description Optional regex constraint for string values. */
            pattern?: string;
        };
        SettingsSchemaResponse: {
            /** @description Bumped when the schema shape changes. */
            version: number;
            nodes: components["schemas"]["SettingsSchemaNode"][];
        };
        ShortLink: {
            code: string;
            /** Format: uri */
            url: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastHitAt?: string | null;
            hitCount?: number;
        };
        AuthUser: {
            /** Format: int64 */
            id: number;
            username: string;
            /** @enum {string} */
            role: "admin" | "viewer";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastLoginAt?: string | null;
            disabled?: boolean;
        };
        AuthMeResponse: {
            user: components["schemas"]["AuthUser"];
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
