/**
 * Runtime zod validators that mirror `components.schemas` in
 * `openapi.yaml`. Consumers (UI + internal Go→TS tooling) call these
 * to validate gateway responses before using them.
 *
 * Invariants (enforced by the compile-time `Equals<...>` assertions
 * at the bottom of each schema section):
 *   - The zod-inferred type is STRUCTURALLY IDENTICAL to the matching
 *     `components['schemas'][<Name>]` type generated by
 *     `openapi-typescript` from `openapi.yaml`.
 *   - If the OpenAPI shape drifts, fix the zod to match — do NOT adapt
 *     the type alias or the assertion to hide the drift.
 *
 * Policy (see `docs/06-agent-rules.md` R2):
 *   - `.strict()` is applied to every hand-written object schema that
 *     does NOT correspond to an OpenAPI entry with
 *     `additionalProperties: true` (or a typed `additionalProperties`
 *     record). This rejects unknown keys at runtime, surfacing spec
 *     drift instead of silently forwarding unknown data.
 *   - `nullable: true` in YAML on an inline field → `.nullable()`.
 *   - `nullable: true` on a `$ref` is silently dropped by
 *     `openapi-typescript` 7 (OpenAPI 3.1 semantics), so the zod
 *     mirror does NOT use `.nullable()` on those sites — it uses
 *     `.optional()` only. If the generated `api.d.ts` starts emitting
 *     `| null` on those fields, update the zod and the assertion.
 */

import { z } from 'zod';
import type { components } from './api.js';
import type { Equals, Expect } from './type-utils.js';

// --------------------------------------------------------------------
// Narrow type aliases (used by the compile-time assertions below).
// These duplicate `index.ts` on purpose — `schemas.ts` must not depend
// on `index.ts` to avoid a circular module graph.
// --------------------------------------------------------------------

type TraceIDType = components['schemas']['TraceID'];
type ErrorCodeType = components['schemas']['ErrorCode'];
type ErrorResponseType = components['schemas']['ErrorResponse'];
type LatLonType = components['schemas']['LatLon'];
type BBoxType = components['schemas']['BBox'];
type RegionStateType = components['schemas']['RegionState'];
type RegionScheduleType = components['schemas']['RegionSchedule'];
type RegionType = components['schemas']['Region'];
type RegionCatalogEntryType = components['schemas']['RegionCatalogEntry'];
type JobStateType = components['schemas']['JobState'];
type JobKindType = components['schemas']['JobKind'];
type JobType = components['schemas']['Job'];
type GeocodeResultType = components['schemas']['GeocodeResult'];
type RouteModeType = components['schemas']['RouteMode'];
type RouteRequestType = components['schemas']['RouteRequest'];
type RouteLegType = components['schemas']['RouteLeg'];
type RouteType = components['schemas']['Route'];
type RouteResponseType = components['schemas']['RouteResponse'];
type IsochroneRequestType = components['schemas']['IsochroneRequest'];
type MatrixRequestType = components['schemas']['MatrixRequest'];
type MatrixResponseType = components['schemas']['MatrixResponse'];
type PoiType = components['schemas']['Poi'];
type PoiCategoryType = components['schemas']['PoiCategory'];
type SettingsTreeType = components['schemas']['SettingsTree'];
type SettingsSchemaNodeType = components['schemas']['SettingsSchemaNode'];
type ShortLinkType = components['schemas']['ShortLink'];
type AuthUserType = components['schemas']['AuthUser'];
type AuthMeResponseType = components['schemas']['AuthMeResponse'];

// --------------------------------------------------------------------
// Primitives / enums / leaf schemas
// --------------------------------------------------------------------

export const TraceIDSchema = z.string();
export type TraceIDSchemaType = z.infer<typeof TraceIDSchema>;
type _AssertTraceID = Expect<Equals<TraceIDSchemaType, TraceIDType>>;

export const ErrorCodeSchema = z.enum([
  'BAD_REQUEST',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'CONFLICT',
  'RATE_LIMITED',
  'INTERNAL',
  'UPSTREAM_UNAVAILABLE',
  'REGION_NOT_READY',
  'REGION_NOT_INSTALLED',
  'REGION_OUT_OF_COVERAGE',
  'INVALID_REGION_NAME',
  'JOB_NOT_FOUND',
  'SCHEMA_MISMATCH',
  'EGRESS_DENIED',
]);
export type ErrorCodeSchemaType = z.infer<typeof ErrorCodeSchema>;
type _AssertErrorCode = Expect<Equals<ErrorCodeSchemaType, ErrorCodeType>>;

export const LatLonSchema = z
  .object({
    lat: z.number().min(-90).max(90),
    lon: z.number().min(-180).max(180),
  })
  .strict();
export type LatLonSchemaType = z.infer<typeof LatLonSchema>;
type _AssertLatLon = Expect<Equals<LatLonSchemaType, LatLonType>>;

// BBox = number[] with exactly 4 elements. The OpenAPI-generated
// type is `number[]` (openapi-typescript does not emit fixed-length
// tuples), so the zod mirror must also infer to `number[]` — hence
// `z.array(...)` rather than `z.tuple(...)`.
export const BBoxSchema = z.array(z.number()).min(4).max(4);
export type BBoxSchemaType = z.infer<typeof BBoxSchema>;
type _AssertBBox = Expect<Equals<BBoxSchemaType, BBoxType>>;

export const RegionStateSchema = z.enum([
  'not_installed',
  'downloading',
  'processing_tiles',
  'processing_routing',
  'processing_geocoding',
  'processing_poi',
  'ready',
  'updating',
  'failed',
  'archived',
]);
export type RegionStateSchemaType = z.infer<typeof RegionStateSchema>;
type _AssertRegionState = Expect<Equals<RegionStateSchemaType, RegionStateType>>;

// RegionSchedule is a free-form string in the spec: 'never' | 'daily'
// | 'weekly' | 'monthly' | <cron string>. We keep it as `z.string()`
// because the set of valid cron strings is not finite; server-side
// validation handles the stricter parse.
export const RegionScheduleSchema = z.string();
export type RegionScheduleSchemaType = z.infer<typeof RegionScheduleSchema>;
type _AssertRegionSchedule = Expect<
  Equals<RegionScheduleSchemaType, RegionScheduleType>
>;

export const JobStateSchema = z.enum([
  'queued',
  'running',
  'succeeded',
  'failed',
  'cancelled',
]);
export type JobStateSchemaType = z.infer<typeof JobStateSchema>;
type _AssertJobState = Expect<Equals<JobStateSchemaType, JobStateType>>;

export const JobKindSchema = z.enum([
  'download_pbf',
  'build_pmtiles',
  'build_valhalla',
  'build_pelias',
  'build_overture',
  'swap_region',
  'update_region',
  'archive_region',
]);
export type JobKindSchemaType = z.infer<typeof JobKindSchema>;
type _AssertJobKind = Expect<Equals<JobKindSchemaType, JobKindType>>;

export const RouteModeSchema = z.enum([
  'auto',
  'bicycle',
  'pedestrian',
  'truck',
]);
export type RouteModeSchemaType = z.infer<typeof RouteModeSchema>;
type _AssertRouteMode = Expect<Equals<RouteModeSchemaType, RouteModeType>>;

// --------------------------------------------------------------------
// Composite schemas
// --------------------------------------------------------------------

export const ErrorResponseSchema = z
  .object({
    error: z
      .object({
        code: ErrorCodeSchema,
        message: z.string(),
        retryable: z.boolean(),
        // `details` in the spec is `additionalProperties: true`, so
        // we accept any runtime shape but still type it as
        // `Record<string, unknown>`.
        details: z.record(z.string(), z.unknown()).optional(),
      })
      .strict(),
    traceId: TraceIDSchema,
  })
  .strict();
export type ErrorResponseSchemaType = z.infer<typeof ErrorResponseSchema>;
type _AssertErrorResponse = Expect<
  Equals<ErrorResponseSchemaType, ErrorResponseType>
>;

// --- Region -----------------------------------------------------------

// `bbox` and `schedule` are declared `nullable: true` against a $ref
// in the YAML, but openapi-typescript 7 drops `| null` on $refs in
// OpenAPI 3.1 mode, so the generated TS has `bbox?: BBox` (not
// `bbox?: BBox | null`). The zod mirror therefore only uses
// `.optional()`, NOT `.nullable()`, on these fields.
export const RegionSchema = z
  .object({
    name: z.string(),
    displayName: z.string(),
    parent: z.string().nullable().optional(),
    sourceUrl: z.string().url(),
    sourcePbfBytes: z.number().int().nullable().optional(),
    sourcePbfSha256: z.string().nullable().optional(),
    bbox: BBoxSchema.optional(),
    state: RegionStateSchema,
    stateDetail: z.string().nullable().optional(),
    lastError: z.string().nullable().optional(),
    installedAt: z.string().datetime({ offset: true }).nullable().optional(),
    lastUpdatedAt: z.string().datetime({ offset: true }).nullable().optional(),
    nextUpdateAt: z.string().datetime({ offset: true }).nullable().optional(),
    schedule: RegionScheduleSchema.optional(),
    diskBytes: z.number().int().nullable().optional(),
    activeJobId: z.string().nullable().optional(),
  })
  .strict();
export type RegionSchemaType = z.infer<typeof RegionSchema>;
type _AssertRegion = Expect<Equals<RegionSchemaType, RegionType>>;

// --- RegionCatalogEntry (self-recursive via `children`) ---------------

export const RegionCatalogEntrySchema: z.ZodType<RegionCatalogEntryType> = z
  .object({
    name: z.string(),
    displayName: z.string(),
    kind: z.enum(['continent', 'country', 'subregion']),
    parent: z.string().nullable().optional(),
    sourceUrl: z.string().url(),
    sourcePbfBytes: z.number().int().nullable().optional(),
    iso3166_1: z.string().nullable().optional(),
    estimatedBuildBytes: z.number().int().nullable().optional(),
    children: z.array(z.lazy(() => RegionCatalogEntrySchema)).optional(),
  })
  .strict();
export type RegionCatalogEntrySchemaType = z.infer<
  typeof RegionCatalogEntrySchema
>;
// `Equals` against the `ZodType<T>`-annotated schema is tautological
// by construction, but we keep the assertion to fail loudly if the
// explicit `ZodType<>` annotation is ever removed.
type _AssertRegionCatalogEntry = Expect<
  Equals<RegionCatalogEntrySchemaType, RegionCatalogEntryType>
>;

// --- Job --------------------------------------------------------------

export const JobSchema = z
  .object({
    id: z.string(),
    kind: JobKindSchema,
    region: z.string().nullable().optional(),
    state: JobStateSchema,
    progress: z.number().min(0).max(1).nullable().optional(),
    message: z.string().nullable().optional(),
    startedAt: z.string().datetime({ offset: true }).nullable().optional(),
    finishedAt: z.string().datetime({ offset: true }).nullable().optional(),
    error: z.string().nullable().optional(),
    parentJobId: z.string().nullable().optional(),
  })
  .strict();
export type JobSchemaType = z.infer<typeof JobSchema>;
type _AssertJob = Expect<Equals<JobSchemaType, JobType>>;

// --- GeocodeResult ----------------------------------------------------

export const GeocodeResultSchema = z
  .object({
    id: z.string(),
    label: z.string(),
    category: z.string().nullable().optional(),
    // `address` in the spec is `additionalProperties: { type: string }`,
    // a fully-open string-keyed map. Leaving it OPEN here; `.strict()`
    // on the outer object still rejects unknown top-level fields.
    address: z.record(z.string(), z.string()).optional(),
    center: LatLonSchema,
    bbox: BBoxSchema.optional(),
    confidence: z.number().min(0).max(1),
    region: z.string().nullable().optional(),
  })
  .strict();
export type GeocodeResultSchemaType = z.infer<typeof GeocodeResultSchema>;
type _AssertGeocodeResult = Expect<
  Equals<GeocodeResultSchemaType, GeocodeResultType>
>;

// --- RouteRequest -----------------------------------------------------

// Fields with a `default` in the OpenAPI spec are emitted as REQUIRED
// by openapi-typescript (server assumes the default was applied on the
// way in). `.default(...)` in zod mirrors that: its `_output` type is
// non-optional, matching the generated TS shape.
export const RouteRequestSchema = z
  .object({
    locations: z.array(LatLonSchema).min(2),
    mode: RouteModeSchema,
    avoidHighways: z.boolean().default(false),
    avoidTolls: z.boolean().default(false),
    avoidFerries: z.boolean().default(false),
    alternatives: z.number().int().min(0).max(5).default(0),
    units: z.enum(['metric', 'imperial']).default('metric'),
    language: z.string().nullable().optional(),
    truck: z
      .object({
        heightMeters: z.number().optional(),
        widthMeters: z.number().optional(),
        weightTons: z.number().optional(),
        lengthMeters: z.number().optional(),
      })
      .strict()
      .nullable()
      .optional(),
  })
  .strict();
export type RouteRequestSchemaType = z.infer<typeof RouteRequestSchema>;
type _AssertRouteRequest = Expect<
  Equals<RouteRequestSchemaType, RouteRequestType>
>;

// --- RouteLeg ---------------------------------------------------------

export const RouteLegSchema = z
  .object({
    summary: z
      .object({
        timeSeconds: z.number().optional(),
        distanceMeters: z.number().optional(),
      })
      .strict(),
    maneuvers: z.array(
      z
        .object({
          instruction: z.string(),
          beginShapeIndex: z.number().int(),
          endShapeIndex: z.number().int().optional(),
          distanceMeters: z.number().optional(),
          timeSeconds: z.number().optional(),
          type: z.string().optional(),
          streetName: z.string().nullable().optional(),
        })
        .strict(),
    ),
    geometry: z
      .object({
        polyline: z.string(),
      })
      .strict(),
  })
  .strict();
export type RouteLegSchemaType = z.infer<typeof RouteLegSchema>;
type _AssertRouteLeg = Expect<Equals<RouteLegSchemaType, RouteLegType>>;

// --- Route ------------------------------------------------------------

export const RouteSchema = z
  .object({
    id: z.string(),
    summary: z
      .object({
        timeSeconds: z.number().optional(),
        distanceMeters: z.number().optional(),
      })
      .strict(),
    legs: z.array(RouteLegSchema),
    waypoints: z.array(LatLonSchema).optional(),
    mode: RouteModeSchema.optional(),
  })
  .strict();
export type RouteSchemaType = z.infer<typeof RouteSchema>;
type _AssertRoute = Expect<Equals<RouteSchemaType, RouteType>>;

// --- RouteResponse ----------------------------------------------------

export const RouteResponseSchema = z
  .object({
    routes: z.array(RouteSchema),
    traceId: TraceIDSchema,
  })
  .strict();
export type RouteResponseSchemaType = z.infer<typeof RouteResponseSchema>;
type _AssertRouteResponse = Expect<
  Equals<RouteResponseSchemaType, RouteResponseType>
>;

// --- IsochroneRequest -------------------------------------------------

export const IsochroneRequestSchema = z
  .object({
    origin: LatLonSchema,
    mode: RouteModeSchema.optional(),
    contoursSeconds: z.array(z.number().int()),
  })
  .strict();
export type IsochroneRequestSchemaType = z.infer<typeof IsochroneRequestSchema>;
type _AssertIsochroneRequest = Expect<
  Equals<IsochroneRequestSchemaType, IsochroneRequestType>
>;

// --- MatrixRequest ----------------------------------------------------

export const MatrixRequestSchema = z
  .object({
    sources: z.array(LatLonSchema),
    targets: z.array(LatLonSchema),
    mode: RouteModeSchema,
  })
  .strict();
export type MatrixRequestSchemaType = z.infer<typeof MatrixRequestSchema>;
type _AssertMatrixRequest = Expect<
  Equals<MatrixRequestSchemaType, MatrixRequestType>
>;

// --- MatrixResponse ---------------------------------------------------

export const MatrixResponseSchema = z
  .object({
    matrix: z.array(
      z.array(
        z
          .object({
            timeSeconds: z.number().optional(),
            distanceMeters: z.number().optional(),
          })
          .strict(),
      ),
    ),
    traceId: TraceIDSchema,
  })
  .strict();
export type MatrixResponseSchemaType = z.infer<typeof MatrixResponseSchema>;
type _AssertMatrixResponse = Expect<
  Equals<MatrixResponseSchemaType, MatrixResponseType>
>;

// --- Poi --------------------------------------------------------------

export const PoiSchema = z
  .object({
    id: z.string(),
    label: z.string(),
    category: z.string().nullable().optional(),
    center: LatLonSchema,
    tags: z.record(z.string(), z.string()).optional(),
    source: z.enum(['overture', 'osm']).optional(),
    region: z.string().nullable().optional(),
  })
  .strict();
export type PoiSchemaType = z.infer<typeof PoiSchema>;
type _AssertPoi = Expect<Equals<PoiSchemaType, PoiType>>;

// --- PoiCategory (self-recursive) -------------------------------------

export const PoiCategorySchema: z.ZodType<PoiCategoryType> = z
  .object({
    id: z.string(),
    label: z.string(),
    icon: z.string().nullable().optional(),
    children: z.array(z.lazy(() => PoiCategorySchema)).optional(),
  })
  .strict();
export type PoiCategorySchemaType = z.infer<typeof PoiCategorySchema>;
type _AssertPoiCategory = Expect<
  Equals<PoiCategorySchemaType, PoiCategoryType>
>;

// --- SettingsTree -----------------------------------------------------

// `additionalProperties: true` on the root → open string-keyed map.
export const SettingsTreeSchema = z.record(z.string(), z.unknown());
export type SettingsTreeSchemaType = z.infer<typeof SettingsTreeSchema>;
type _AssertSettingsTree = Expect<
  Equals<SettingsTreeSchemaType, SettingsTreeType>
>;

// --- SettingsSchemaNode (self-recursive) ------------------------------

export const SettingsSchemaNodeSchema: z.ZodType<SettingsSchemaNodeType> = z
  .object({
    key: z.string().optional(),
    type: z.enum([
      'object',
      'string',
      'integer',
      'number',
      'boolean',
      'enum',
      'array',
    ]),
    description: z.string().optional(),
    default: z.unknown().optional(),
    enumValues: z.array(z.string()).optional(),
    minimum: z.number().optional(),
    maximum: z.number().optional(),
    items: z.lazy(() => SettingsSchemaNodeSchema).optional(),
    properties: z
      .record(z.string(), z.lazy(() => SettingsSchemaNodeSchema))
      .optional(),
    uiGroup: z.string().optional(),
    unit: z.string().optional(),
    step: z.number().optional(),
    itemType: z.enum(['string', 'integer', 'number', 'boolean', 'object']).optional(),
    readOnly: z.boolean().optional(),
    pattern: z.string().optional(),
  })
  .strict();
export type SettingsSchemaNodeSchemaType = z.infer<
  typeof SettingsSchemaNodeSchema
>;
type _AssertSettingsSchemaNode = Expect<
  Equals<SettingsSchemaNodeSchemaType, SettingsSchemaNodeType>
>;

// --- SettingsSchemaResponse ------------------------------------------

type SettingsSchemaResponseType = components['schemas']['SettingsSchemaResponse'];

export const SettingsSchemaResponseSchema: z.ZodType<SettingsSchemaResponseType> = z
  .object({
    version: z.number().int(),
    nodes: z.array(SettingsSchemaNodeSchema),
  })
  .strict();
export type SettingsSchemaResponseSchemaType = z.infer<
  typeof SettingsSchemaResponseSchema
>;
type _AssertSettingsSchemaResponse = Expect<
  Equals<SettingsSchemaResponseSchemaType, SettingsSchemaResponseType>
>;

// --- ShortLink --------------------------------------------------------

export const ShortLinkSchema = z
  .object({
    code: z.string(),
    url: z.string().url(),
    createdAt: z.string().datetime({ offset: true }),
    lastHitAt: z.string().datetime({ offset: true }).nullable().optional(),
    hitCount: z.number().int().optional(),
  })
  .strict();
export type ShortLinkSchemaType = z.infer<typeof ShortLinkSchema>;
type _AssertShortLink = Expect<Equals<ShortLinkSchemaType, ShortLinkType>>;

// --- AuthUser + AuthMeResponse ----------------------------------------

export const AuthUserSchema = z
  .object({
    id: z.number().int(),
    username: z.string().min(1),
    role: z.enum(['admin', 'viewer']),
    createdAt: z.string().datetime({ offset: true }).optional(),
    lastLoginAt: z.string().datetime({ offset: true }).nullable().optional(),
    disabled: z.boolean().optional(),
  })
  .strict();
export type AuthUserSchemaType = z.infer<typeof AuthUserSchema>;
type _AssertAuthUser = Expect<Equals<AuthUserSchemaType, AuthUserType>>;

export const AuthMeResponseSchema = z
  .object({
    user: AuthUserSchema,
  })
  .strict();
export type AuthMeResponseSchemaType = z.infer<typeof AuthMeResponseSchema>;
type _AssertAuthMeResponse = Expect<
  Equals<AuthMeResponseSchemaType, AuthMeResponseType>
>;

// --------------------------------------------------------------------
// Parity-guard exports — referencing the assertion aliases keeps
// `noUnusedLocals` quiet while ensuring the compiler evaluates them.
// Do not remove.
// --------------------------------------------------------------------

export type _ParityGuards = [
  _AssertTraceID,
  _AssertErrorCode,
  _AssertLatLon,
  _AssertBBox,
  _AssertRegionState,
  _AssertRegionSchedule,
  _AssertJobState,
  _AssertJobKind,
  _AssertRouteMode,
  _AssertErrorResponse,
  _AssertRegion,
  _AssertRegionCatalogEntry,
  _AssertJob,
  _AssertGeocodeResult,
  _AssertRouteRequest,
  _AssertRouteLeg,
  _AssertRoute,
  _AssertRouteResponse,
  _AssertIsochroneRequest,
  _AssertMatrixRequest,
  _AssertMatrixResponse,
  _AssertPoi,
  _AssertPoiCategory,
  _AssertSettingsTree,
  _AssertSettingsSchemaNode,
  _AssertShortLink,
  _AssertAuthUser,
  _AssertAuthMeResponse,
];
